services:
  iapping:
    build: ..
    ports:
      - "9999:9999"
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
    command: >-
      --target-url http://demo:8000
      --jwks-address 0.0.0.0:9999
      --audience https://example.com
      --subjects 0.0.0.0:9001,user1@example.com
      --subjects 0.0.0.0:9002,user2@example.com,sample_access_level
      --subjects 0.0.0.0:9003,user3@example.com,can_have_two,access_levels
  demo:
    build: .
    ports:
      - "8000:8000"
    environment:
      - IAP_JWKS_URL=http://iapping:9999/jwks.json
      - IAP_JWT_AUDIENCE=https://example.com
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000

  # Health checks so tests can easily wait before starting.
  # Separate services since we don't have curl in the docker
  # images (and don't want to add it there).
  health-check-demo:
    image: alpine/curl
    entrypoint: ["tail", "-f", "/dev/null"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://demo:8000/health"]
      interval: 1s
      timeout: 1s
      retries: 5
  health-check-iapping:
    image: alpine/curl
    entrypoint: ["tail", "-f", "/dev/null"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://iapping:9001/health"]
      interval: 1s
      timeout: 1s
      retries: 5
